INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (1, 'AZARE', 1, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (2, 'AZARE TOWN', 1, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (3, 'COE/FIRE SERVICE', 1, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (4, 'FGC/RADIO MONITORING', 1, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (5, 'GAMAWA/DAMBAM', 2, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (6, 'GRA AZARE', 1, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (7, 'GRA MISAU', 3, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (8, 'HARDAWA', 3, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (9, 'JAMAARE', 4, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (10, 'EMIR PALACE JAMAARE', 5, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (11, 'FED. LOWCOST JAMAARE', 5, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (12, 'MISAU', 3, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (13, 'MISAU TOWN', 3, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (14, 'SHIRA-YANA', 5, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (15, 'AIRFORCE BASE BAUCHI', 6, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (16, 'AMINU STREET', 7, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (17, 'ATBU', 8, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (18, 'ATBU PERMANENT SITE', 6, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (19, 'BANK ROAD', 9, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (20, 'BARRACK', 7, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (21, 'STADIUM', 7, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (22, 'BOGORO I', 10, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (23, 'BOGORO II', 10, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (24, 'DASS', 10, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (25, 'FED. LOW COST BAUCHI', 11, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (26, 'YELWA', 10, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (27, 'FED. LOW COST BAUCHI', 10, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (28, 'GOVT. HOUSE BAUCHI', 8, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (29, 'GRA/PALACE', 11, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (30, 'GUBI DAM', 12, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (31, 'GWALLAMEJI', 10, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (32, 'INDUSTRIAL BAUCHI', 9, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (33, 'MUDA LAWAL', 12, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (34, 'NABORDO', 8, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (35, 'NINGI', 6, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (36, '33KV TIAMIN', 13, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (37, 'NINGI TOWN', 6, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (38, 'RAILWAY', 11, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (39, 'RAN ROAD', 7, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (40, 'TEACHING HOSPITAL', 12, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (41, 'TUDUN SALMANU', 7, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (42, 'WATER WORKS BAUCHI', 7, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (43, 'WUNTI ROAD', 12, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (44, 'GUBI', 12, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (45, 'YANKARI', 14, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (46, 'YUGUDA FARM', 9, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (47, 'BARIKIN LADI TOWN', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (48, 'BUKURU', 16, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (49, 'BUKURU TOWN', 16, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (50, 'COCA COLA', 17, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (51, 'DADIN KOWA', 17, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (52, 'DEDICATED (NASCO)', 17, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (53, 'DENGI TOWN', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (54, 'DOROWA', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (55, 'GANAWURI (NESCO)', 18, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (56, 'GENERAL HOSPITAL PANKSHIN', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (57, 'GINDIRI', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (58, 'GRA SHENDAM', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (59, 'GURA TOP/MAZ.', 19, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (60, 'HWOLSHE', 20, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (61, 'IBRAHIM TAIWO', 20, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (62, 'ANGLO JOS', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (63, 'INDUSTRIAL JOS', 17, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (64, 'J.D. GOMWALK', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (65, 'KUFFEN', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (66, 'LIBERTY DAM', 20, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (67, 'MAKERI', 17, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (68, 'MANGU TOWN', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (69, 'MANGU TOWN', 22, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (70, 'MBAR TOWN', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (71, 'MIANGO 3.3KV', 18, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (72, 'NEW GOVT. HOUSE JOS', 19, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (73, 'NIPSS KURU', 16, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (74, 'NVRI', 16, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (75, 'PAJAT', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (76, 'PANKSHIN FCE', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (77, 'PILGANI', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (78, 'POLICE STAFF COLLEGE/POLY', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (79, 'RAYFIELD', 19, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (80, 'SCIENCE SCH. KURU', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (81, 'SECRETARIAT', 20, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (82, 'TOTAL', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (83, 'TUDUN WADA JOS', 20, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (84, 'VOM', 16, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (85, 'WASE GARKUWA', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (86, 'WASE PRISON', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (87, 'YAKUBU GOWON DAM', 16, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (88, 'ZARTEX', 15, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (89, 'ZAWAN', 16, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (90, 'DCP II', 23, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (91, 'KATSINA ALA', 24, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (92, 'GBOKO/ADIKPO', 24, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (93, 'MAKURDI TOWN', 25, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (94, 'KATSINA ALA', 26, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (95, 'VANDEIKYA', 24, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (96, 'WUKARI', 27, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (97, 'YANDEV', 28, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (98, 'MAKURDI TOWN', 28, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (99, 'KATSINA ALA', 28, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (100, 'WUKARI', 28, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (101, 'TARAKU', 28, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (102, 'BCGA', 30, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (103, 'BYPASS', 31, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (104, 'CBN GOMBE', 32, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (105, 'DADIN KOWA WATER WORKS (3.3kV)', 31, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (106, 'DARAZO TOWN', 33, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (107, 'DARAZO/DUKKU', 33, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (108, 'DOMA', 30, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (109, 'EMIR\'S PALACE DARAZO', 33, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (110, 'FED. LOW COST GOMBE', 34, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (111, 'FIKA', 35, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (112, 'FMC', 32, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (113, 'FMC GOMBE', 32, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (114, 'FMC STAFF QUARTERS GOMBE', 32, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (115, 'GOMBE STATE UNIVERSITY', 34, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (116, 'GOMBE TOWN', 34, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (117, 'GOVT. HOUSE GOMBE', 36, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (118, 'GRA GOMBE', 34, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (119, 'KUMO', 37, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (120, 'KALSHINGI TOWN I', 38, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (121, 'KALSHINGI TOWN II', 38, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (122, 'BILLIRI', 38, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (123, 'KALTUNGO', 39, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (124, 'KUMO TOWN 11kV', 37, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (125, 'MALLAM INNA', 34, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (126, 'MALLAM SIDI', 40, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (127, 'NAFADA TOWN', 35, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (128, 'NNPC DEPORT GOMBE (3.3kV)', 36, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (129, 'PANTAMI', 36, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (130, 'PANTAMI', 31, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (131, 'RIYEL', 34, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (132, 'RIYEL', 31, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (133, 'SHONGO', 36, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (134, 'TABRA PUMPING STATION (3.3kV)', 31, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (135, 'TUDUN WADA GOMBE', 34, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (136, 'TUNFURE', 36, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (137, 'WATER WORKS GOMBE', 31, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (138, 'ARMY BARRACKS', 41, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (139, 'BAPTIST', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (140, 'BAUCHI RING RD', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (141, 'BAUCHI ROAD TOWNSHIP', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (142, 'CONGO', 43, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (143, 'DILIMI', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (144, 'DOGON DUTSE', 43, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (145, 'FOBUR', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (146, 'GADA BIU', 43, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (147, 'JUTH', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (148, 'JUTH', 44, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (149, 'JUTH I', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (150, 'JUTH II', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (151, 'KATAKO', 43, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (152, 'PRIVATE+S6647+E:E', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (153, 'LAMINGO', 42, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (154, 'MURTALA MOHAMMED', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (155, 'NARAGUTA', 43, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (156, 'NASARAWA', 43, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (157, 'NNPC DEPORT JOS 3.3KV', 45, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (158, 'NNPC JOS', 45, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (159, 'POLO', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (160, 'RANTYA', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (161, 'RUKUBA', 41, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (162, 'RUKUBA ROAD', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (163, 'STATE LOWCOST', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (164, 'TAFAWA BALEWA', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (165, 'TORO', 46, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (166, 'UNIJOS DEDICATED', 43, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (167, 'UTAN', 47, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (168, 'WEST OF MINES', 21, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (169, 'ZARIA ROAD 11KV', 47, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (170, 'ZARIA ROAD', 47, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (171, 'AIRFORCE MAKURDI', 48, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (172, 'BARRACKS ROAD', 49, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (173, 'BBL', 48, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (174, 'BSU', 48, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (175, 'CBN MAKURDI', 49, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (176, 'DAUDU', 50, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (177, 'DAUDU', 51, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (178, 'DISTRICT', 48, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (179, 'GBOKO ROAD', 48, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (180, 'GOVT. HOUSE MAKURDI', 49, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (181, 'GRA MAKURDI', 49, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (182, 'HIGH LEVEL', 49, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (183, 'INDUSTRIAL MAKURDI', 50, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (184, 'MAKURDI TOWN 11KV', 49, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (185, 'NAKA ROAD', 50, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (186, 'NAKA ROAD', 51, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (187, 'NASME', 50, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (188, 'NNPC MAKURDI', 48, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (189, 'NNPC Deport Makurdi (3.3kV)', 48, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (190, 'NORTH BANK', 50, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (191, 'SRS', 50, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (192, 'SRS', 51, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (193, 'UNIAGRIC', 50, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (194, 'WURUKUM', 49, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (195, 'ALIADE', 52, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (196, 'ANKPA', 53, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (197, 'BENPOLY', 53, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (198, 'IGBANOMAJE', 52, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (199, 'OBARIKE TOWN', 54, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (200, 'OJU', 54, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (201, 'OJU I', 54, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (202, 'OJU II', 54, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (203, 'OKPOGA', 53, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (204, 'OLD ENUGU ROAD', 53, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (205, 'OTADA', 52, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (206, 'OTUKPO TOWN', 55, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (207, 'TARAKU', 52, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (208, 'UGBOKOLO', 53, NULL, NULL);
INSERT INTO `feeder11s` (`id`, `name`, `feeder33_id`, `created_at`, `updated_at`) VALUES (209, '', 0, NULL, NULL);
