INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (1, 'AZARE', 7, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (2, 'GAMAWA/DAMBAM', 7, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (3, 'MISAU', 7, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (4, 'JAMAARE', 7, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (5, 'JAMA\'ARE', 7, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (6, 'NINGI', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (7, 'WATER WORKS BAUCHI', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (8, 'NABORDO', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (9, 'YUGUDA FARM', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (10, 'DASS', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (11, 'GRA/PALACE', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (12, 'GUBI', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (13, '33KV TIAMIN', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (14, 'YANKARI', 6, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (15, 'DOROWA', 4, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (16, 'BUKURU', 4, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (17, 'MAKERI', 4, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (18, 'NESCO', 4, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (19, 'NEW GOVT. HOUSE JOS', 4, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (20, 'SECRETARIAT', 4, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (21, 'ANGLO JOS', 1, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (22, 'DOROWA ', 4, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (23, 'DCP II', 3, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (24, 'KATSINA ALA', 3, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (25, 'MAKURDI TOWN', 3, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (26, 'KASTINA ALA', 3, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (27, 'WUKARI', 3, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (28, 'YANDEV', 3, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (29, 'YANDEV', 5, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (30, 'DOMA', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (31, 'WATER WORKS GOMBE', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (32, 'FMC', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (33, 'DARAZO/DUKKU', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (34, 'GOMBE TOWN', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (35, 'FIKA', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (36, 'SHONGO', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (37, 'KUMO', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (38, 'BILLIRI', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (39, 'KALTUNGO', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (40, 'MALLAM SIDI', 8, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (41, 'RUKUBA', 1, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (42, 'JUTH', 1, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (43, 'DOGON DUTSE', 1, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (44, 'JUTH ', 1, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (45, 'NNPC JOS', 1, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (46, 'TORO', 1, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (47, 'ZARIA ROAD', 1, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (48, 'NNPC MAKURDI', 2, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (49, 'BARRACKS ROAD', 2, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (50, 'NORTH BANK', 2, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (51, 'NORTHBANK', 2, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (52, 'TARAKU', 5, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (53, 'ANKPA', 5, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (54, 'OJU', 5, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (55, 'ASA', 5, NULL, NULL);
INSERT INTO `feeder33s` (`id`, `name`, `business_unit_id`, `created_at`, `updated_at`) VALUES (56, '', 0, NULL, NULL);
